-- Wygenerowane z manual-test-data/procedures.md — patrz 01-domains.sql

SET TERM ^ ;

CREATE PROCEDURE GET_EXPIRING_STOCK_ITEMS (
  DAYS INTEGER
)
RETURNS (ID INTEGER, NAME VARCHAR(100), EXPIRATION_DATE DATE)
AS
BEGIN
  FOR SELECT ID, NAME, EXPIRATION_DATE FROM STOCK_ITEMS
      WHERE EXPIRATION_DATE IS NOT NULL AND EXPIRATION_DATE <= CURRENT_DATE + :DAYS
      INTO :ID, :NAME, :EXPIRATION_DATE
  DO SUSPEND;
END^

SET TERM ; ^
